### ISSUE TITLE
Improve csx tests

### ISSUE THREAD

**Issue by matheusps** [matheusps/clssx#1]
Add tests for `undefined` and `null` on `csx.test`

**Comment by taksuparth** [comment]
@matheusps giving `undefined` or `null` in csx function will result in a type error, because it expects argument's type to be either string, number or object with key value pair. So, no need to write test cases for scenarios which is not going to happen. Or we can change type of csx function to take input undefined and null and then write test cases for that.

**Comment by matheusps** [comment]
@taksuparth Thanks in advance for contributing. I think we can change the signature to accept these values and if they are passed, return an empty string. Check issue #3

**Comment by taksuparth** [comment]
@matheusps sounds cool! I will take that up.
